* Module and Package
  * How to see the source codes

In [5]:
import numpy as np
import pandas as pd
from math import sqrt
#from math import *

* numpy and Ndarray
  * Why numpy -- Fast, Standard ...
  * composition of a Ndarray: dtype, ndim, shape ... 
  * indexing and slicing
  * calculation and broadcast
  * useful functions

In [13]:
arr = np.array([1,2,3], dtype=np.float64, ndmin=1)
arr.shape

(3,)

In [22]:
# how to create
arr = np.array([1,2,3], dtype=np.float64, ndmin=2)
print('array1: ',arr,'\n\n')


# about the dimension 
# Dimensions from left to right correspond to brackets from outside to inside
arr1 = np.ones((2,3,4))
print('array2: ',arr1, '\n\n\n')

# (1,) != (1,1)    Be careful  

arr2 = np.array(range(24)).reshape((2,3,4))
print('array3: ', arr2)

array1:  [[1. 2. 3.]] 


array2:  [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]] 



array3:  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [23]:
# Indexing
print(arr2[-2,-1])

# Slicing
print(arr2[-1,::2,::2])

# Boolean Slicing
arr2[arr2>14]

[ 8  9 10 11]
[[12 14]
 [20 22]]


array([15, 16, 17, 18, 19, 20, 21, 22, 23])

In [26]:
# when shapes are the same
arr1 = arr1.reshape((8,3))
arr2 = arr2.reshape((8,3))

print(arr1*2,arr2, (arr1*2) ** arr2,sep='\n')

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[1.000000e+00 2.000000e+00 4.000000e+00]
 [8.000000e+00 1.600000e+01 3.200000e+01]
 [6.400000e+01 1.280000e+02 2.560000e+02]
 [5.120000e+02 1.024000e+03 2.048000e+03]
 [4.096000e+03 8.192000e+03 1.638400e+04]
 [3.276800e+04 6.553600e+04 1.310720e+05]
 [2.621440e+05 5.242880e+05 1.048576e+06]
 [2.097152e+06 4.194304e+06 8.388608e+06]]


In [116]:
# Broadcast
arr = np.array([0,1,2])  # arr = [1,2,3]

arr + arr2

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13],
       [12, 14, 16],
       [15, 17, 19],
       [18, 20, 22],
       [21, 23, 25]])

* pandas
  * Series
    * Composition : name, dtype, index, values
  * DataFrame
    * Composition : index, columns, values -- set of Series

In [28]:
# creation
# using two lists
s = pd.Series(data=[89,88,87,91],index=['A','B','C','D'],name='Scores')
print(s)

# using dict
pd.Series({'A':89,'B':88,'C':87,'D':91},name='Scores')


A    89
B    88
C    87
D    91
Name: Scores, dtype: int64


A    89
B    88
C    87
D    91
Name: Scores, dtype: int64

In [30]:
# Indexing
print(s[1],s[-2]) # using numerical index 

print(s['A'])     # using  specified index


# Slicing
print(s[0:3],s['A':'C'],s[['A','C','D']],sep='\n') # Mind that Numerical indexing is different from Specified Indexing in the end of Slicing !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

print('\nBoolean Indexing: \n',s[s>89])

88 87
89
A    89
B    88
C    87
Name: Scores, dtype: int64
A    89
B    88
C    87
Name: Scores, dtype: int64
A    89
C    87
D    91
Name: Scores, dtype: int64

Boolean Indexing: 
 D    91
Name: Scores, dtype: int64


In [31]:
# Creating a df
df1 = pd.DataFrame(data={'HU':[89,89,89,89],'CHEN':[90,90,90,91],'DU':[98,99,100,101]},index=['A','B','C','D'])

# index
# columns indexing
print(df1['HU']) # 单列
print(df1[['HU','DU']]) # 多列*
# 只用 []  只能索引 “列”，不支持多维（可以做布尔索引



A    89
B    89
C    89
D    89
Name: HU, dtype: int64
   HU   DU
A  89   98
B  89   99
C  89  100
D  89  101


In [144]:
# loc & iloc  ----> 支持slicing
df1.loc['A':'C','HU':"CHEN"]    # 按 “名” 索引
df1.iloc[:3,:2]                 # 按 “位” 索引

HU  CHEN
A  89    90
B  89    90
C  89    90

In [32]:
# 关于逻辑运算  *
# ~ 、& 、|、all()、any()
print(df1>100)
print((df1>100).any(axis=0))  # axis = 0 --> 关于列； axis = 1 --> 关于行

      HU   CHEN     DU
A  False  False  False
B  False  False  False
C  False  False  False
D  False  False   True
HU      False
CHEN    False
DU       True
dtype: bool


In [45]:
# 实用操作 1  -----> 查找(布尔索引) * 
# 多条件 一定 一定 一定 【括号】
#print(df1.loc[(df1>100).any(axis=1),(df1>100).any()])  # 有门课 有同学 超过了 100分

print(df1.loc[((df1==100).any(axis=1)) & ((df1<90).any(axis=1)),:]) # 有门课，有的同学没有4.0，有的同学100分，差异很大

   Hrq  CXX  Dyf
C   89   90  100


In [175]:
# A 股 日度交易数据
data = pd.read_csv(r'C:\DataBank\CSMAR\TRD_Dalyr.csv')

In [ ]:
data = data[(data['Markettype']==1) | (data['Markettype']==4)].copy()  # 布尔索引

In [200]:
# inplace *
data = data.sort_values(by=['Stkcd','Trddt'],ascending=[0,1],inplace=False)
data.sort_values(by=['Stkcd','Trddt'],ascending=[1,1],inplace=True)

In [217]:
# about Na
data.isna().any() # 查询哪些列是否存在缺失值

data[data.isna().any(axis=1)] # 查询在哪一行

data.dropna(subset=['Stkcd','Trddt'],inplace=False)  

In [222]:
# duplicates
data[data.duplicated(subset=['Stkcd','Trddt'])] # 寻找 重复

data.drop_duplicates() # subset, axis, inplace


Empty DataFrame
Columns: [Stkcd, Trddt, Clsprc, Dnshrtrd, Dsmvosd, Dretwd, Markettype, Trdsta]
Index: []

* 数据下载
  * CSMAR
  * WIND

数据操作：

单表操作
sort_values
drop
dropna
drop_duplicates

groupby 与 rolling 、 聚集函数、 nth()

merge