In [1]:
# about Package

# import math as m
# m.sqrt(4)


# from math import sqrt
# sqrt(4)


# from math import *
# acos(1)

### Pandas 


* **what does pandas stand for? Giant pandas?**
  * **NO!** It's for three data structures:
    * $pan$   for Panel
    * $da$    for Dataframe
    * $s$     for Series


* **How can we do with Pandas?**
  * visualize data simply
  * manipulate data efficiently and elegantly
  * input and output data easily

In [2]:
import pandas as pd

### Series


In [3]:
# Create one series

s = pd.Series(data=[89,88,87,91],index=['A','B','C','D'],name='Scores')
print(s)

# using dict
s = pd.Series({'A':89,'B':88,'C':87,'D':91},name='Scores')

A    89
B    88
C    87
D    91
Name: Scores, dtype: int64


#### Composite of Series

In [4]:
# index

print((s.index))
print(type(s.index))

Index(['A', 'B', 'C', 'D'], dtype='object')
<class 'pandas.core.indexes.base.Index'>


In [5]:
# value

print(s.values)
print(type(s.values))

[89 88 87 91]
<class 'numpy.ndarray'>


In [6]:
# name

print(s.name)
print(type(s.name))

Scores
<class 'str'>


#### Operation on Series

#### 1. Indexing

In [26]:
# index by the specified index
print("s['A']:\t",s['A'])

# index by numerical index
print("s[0]:\t",s[0])

s['A']:	 89
s[0]:	 89


In [27]:
# loc

print("s.loc['A']:\t",s.loc['A'])     #Mind that it's [] not () !

s.loc['A']:	 89


In [28]:
s.loc[0]

KeyError: 0

In [29]:
# iloc

print("s.iloc[0]:\t",s.iloc[0])     #Mind that it's [] not () !

s.iloc[0]:	 89


In [30]:
s.iloc['A']

TypeError: Cannot index by location index with a non-integer key

**Mind that : loc is for specified index, rather iloc is for numerical index**

In [120]:
# Multi indexing (index by a list)

print("s[['A','D']]",)
print(s[['A','D']])


print("\n\ns[[0,3]]",)
print(s[[0,3]])

s[['A','D']]
A    89
D    91
Name: Scores, dtype: int64


s[[0,3]]
A    89
D    91
Name: Scores, dtype: int64


***what is the different between input a list and a value?***

In [31]:
print("s['A'] : \n",s['A'])

print("\ns[['A']]\n",s[['A']])

s['A'] : 
 89

s[['A']]
 A    89
Name: Scores, dtype: int64


**Mind that : when you index by a list, it returns a Series (retain type). When you index by a value, it returns a value (type demotion)**

#### 2. slicing

In [88]:
# it's as the same with that in list

print("s['A':'B']\n",)
print(s['A':'B'])


print("\n\ns.loc['A':'B']")
print(s.loc['A':'B'])

s['A':'B']

A    89
B    88
Name: Scores, dtype: int64


s.loc['A':'B']
A    89
B    88
Name: Scores, dtype: int64


In [89]:
print("s[0:1]\n")
print(s[0:1])


print("\ns.iloc[0:1]\n")
print(s.iloc[0:1])

s[0:1]

A    89
Name: Scores, dtype: int64

s.iloc[0:1]

A    89
Name: Scores, dtype: int64


##### **What do you learn?**  
***1. iloc doesn't include the end, just like range***  
***2. when specified index is not numerical, the range end will be included !!!***

##### What happens if the specified index is numerical?

In [37]:
temp = s.copy()  # copy is for cut the connection between s and temp 
temp.index = range(len(temp))
temp

0    120
1     88
2     87
3     91
Name: Scores, dtype: int64

In [105]:
temp[0:3]

0    89
1    88
2    87
Name: Scores, dtype: int64

In [106]:
temp.loc[0:3]

0    89
1    88
2    87
3    91
Name: Scores, dtype: int64

In [107]:
temp.iloc[0:3]

0    89
1    88
2    87
Name: Scores, dtype: int64

#### 3. assignment

In [108]:
temp[3] = 100  # assignment is pythonic
temp

0     89
1     88
2     87
3    100
Name: Scores, dtype: int64

In [109]:
temp[:2] = 100  # it's the same with .iloc
temp

0    100
1    100
2     87
3    100
Name: Scores, dtype: int64

In [112]:
temp[:2] = [89,88]
temp

0     89
1     88
2     87
3    100
Name: Scores, dtype: int64

In [40]:
temp[[0,3]] = [89,88]
temp

0    89
1    88
2    87
3    88
Name: Scores, dtype: int64

#### 4. Aggregation

In [ ]:
s.aggregate([max,min,'mean','std','skew','kurtosis'])

In [135]:
s.min()

max         91.000000
min         87.000000
mean        88.750000
std          1.707825
skew         0.752837
kurtosis     0.342857
Name: Scores, dtype: float64

In [50]:
s.agg([max,min,'mean','std','skew','kurtosis'])

max         87.000000
min         87.000000
mean        96.500000
std         15.758596
skew         1.931832
kurtosis     3.756533
Name: Scores, dtype: float64

***Why max and min are func type not str?***

In [ ]:
# max and min are built-in func

def max(li):
    return min(li)

print(s.max())
print(max(s))

### Dataframe

In [97]:
# create a dataframe
df = pd.DataFrame(data={'HU':[89,89,89,89],'CHEN':[90,90,90,91],'DU':[98,99,100,101]},index=['A','B','C','D'])

df

HU  CHEN   DU
A  89    90   98
B  89    90   99
C  89    90  100
D  89    91  101

#### Dataframe composition

In [98]:
# index
df.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [99]:
# columns
df.columns

Index(['HU', 'CHEN', 'DU'], dtype='object')

**index and columns are the same type**

In [100]:
type(df.columns)

pandas.core.indexes.base.Index

In [101]:
# value
print(df.values)
print(type(df.values))

[[ 89  90  98]
 [ 89  90  99]
 [ 89  90 100]
 [ 89  91 101]]
<class 'numpy.ndarray'>


**A Dataframe is a Serie of series !**

#### Operation on Dataframe

#### 1. Indexing & Slicing

**the logic of indexing and slicing in dataframe is completely the same with that of Series**

In [102]:
df

HU  CHEN   DU
A  89    90   98
B  89    90   99
C  89    90  100
D  89    91  101

In [103]:
# [] only to get columns
df[['HU']]

HU
A  89
B  89
C  89
D  89

In [104]:
# indexing by specified index
df.loc[['A','C'],['HU']]

HU
A  89
C  89

In [105]:
# slicing by specified index
df.loc[['A','C'],:'DU']

HU  CHEN   DU
A  89    90   98
C  89    90  100

In [106]:
# indexing by numerical index
df.iloc[[0,2],[0]]

HU
A  89
C  89

In [107]:
# slicing by numerical index
df.iloc[[0,2],:-1]

HU  CHEN
A  89    90
C  89    90

#### 2. Assignment

In [108]:
df.iloc[[0,2],[0]] = 100
df

HU  CHEN   DU
A  100    90   98
B   89    90   99
C  100    90  100
D   89    91  101

In [109]:
import numpy as np
df.iloc[[0,2],[0]] = np.array([[89,88]]).T   # mind the shape
df

HU  CHEN   DU
A  89    90   98
B  89    90   99
C  88    90  100
D  89    91  101

In [120]:
# append a column 
df['GAN'] = pd.Series([90,91,92],index=['A','C','E'])
df = df.loc[['B','A','D','C'],:]
df['WANG'] = [99,98,97,100]
df

**column assignment is the merge of index !!!!!**

#### 4.agg

In [125]:
# stat the mean scores of each course
df.mean(axis=1)  

B    94.25
A    93.00
D    94.50
C    93.80
dtype: float64

In [127]:
df.agg(['mean','min','max','std','skew'],axis=1)

mean   min    max       std      skew
B  94.25  89.0   99.0  5.500000 -0.028550
A  93.00  89.0   98.0  4.582576  0.571523
D  94.50  89.0  101.0  5.507571  0.323231
C  93.80  88.0  100.0  5.761944  0.445905

**mind the parameter axis. Default value of this parameter in most functions in pandas is 0 (by column), so we need to choose axis=1 (by row) manually**